version: "3.7"
services:
  monolith:
    build:
      context: ./monolith
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./monolith:/app
  react-attendees:
    image: node:latest
    command: npm start
    working_dir: /app
    volumes:
      - ./ghi/weather:/app
    environment:
      - HOST=0.0.0.0
      - PORT=3001
    ports:
      - "3001:3001"
